### PR TITLE
Remove keda

### PR DESCRIPTION
**Pull request by danielhoherd**
## Description

Remove keda from astronomer/astronomer helm chart.

## Related Issues

https://github.com/astronomer/issues/issues/4441

## Testing

The only testing I've done are the regular CI tests, which should be enough IMHO.

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@danielhoherd  Should we add steps or point how to integrate keda with astronomer if we are removing them completely

**Comment by danielhoherd** [comment]
> @danielhoherd Should we add steps or point how to integrate keda with astronomer if we are removing them completely

I'm counting on the docs team to handle anything related to that.

**Review by cmarteepants — APPROVED** [review]

**Review by rbankston — APPROVED** [review]
Those changes look good to me.

**Comment by jwitz** [comment]
Is this being introduced alongside a Software release, or is this already out?

**Comment by jwitz** [comment]
As far as I know, the only non-release note docs we would have to update are any code configurations that mention keda as a small part of a larger config ([example](https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/example_dags/example_gcs.py))

**Comment by jwitz** [comment]
Whoops wrong link! Meant here: https://docs.astronomer.io/software/namespace-pools#step-1-configure-namespaces

**Pull request merged**
