### PR TITLE
Add support for AC 1.10.5 & 1.10.10 Docker images

### PR DESCRIPTION
**Pull request by kaxil**
Depends on https://github.com/astronomer/astronomer/pull/702

Based on the conversation in https://github.com/astronomer/astronomer/pull/659

**Note**: Only review last commit: https://github.com/astronomer/astronomer/pull/703/commits/c19043c68a07dee5028d2a439da5435dbc4cc731

### CODE REVIEW

**Comment by ashb** [comment]
@kaxil I've merged the other PR, can you rebase please?

**Comment by kaxil** [comment]
Done

**Comment by ashb** [comment]
Sooo, what are we doing about the order @schnie?

**Comment by vishwas-astro** [comment]
hmm .. @ashb isn't the order determined by the code here: https://github.com/astronomer/houston-api/blob/59d62c2803ca2f60af106826d81acf1c0a930389/src/lib/deployments/config/index.js#L632

**Comment by ashb** [comment]
Oh yes good point Vishwas, the order no longer matters since 0.15, as we do a sort based on version inside Huston, so for the sake of tidyness lets have it in sorted order in the file too please @kaxil

**Comment by kaxil** [comment]
Aah didn't knew that it was sorted, yes will fix the order. Thanks Vishwas & Ash

**Comment by kaxil** [comment]
@ashb I have added 1.10.10-2 docker images too

**Comment by kaxil** [comment]
Please feel to merge it ( I don't have perms)

**Pull request merged**
