### PR TITLE
Removed hardcoded subversion

### PR DESCRIPTION
**Pull request by shmanu017**
## Description

Upgrade script 0.23-to-0.25 is hard coded to upgrade to 0.25.6 instead of highest subversion , removed the subversion.

## Related Issues

https://github.com/astronomer/issues/issues/4507

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@shmanu017 - upgrader test is failing

**Comment by danielhoherd** [comment]
I seem to recall that we tried this and it caused problems somewhere, but I can't recall where. It would be good to dig around and see if we documented problems in any past tickets or PRs.

**Comment by andriisoldatenko** [comment]
@shmanu017 please resolve conflicts. 
+1 for @danielhoherd's point

**Review by santoshr1016 — APPROVED** [review]
👍

**Comment by shmanu017** [comment]
Test passed after re-running it.Hence , merged it release-0.25

**Pull request merged**
