### PR TITLE
remove rbac conditional changes

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

remove rbac conditional changes

This is a continutation from the PR https://github.com/astronomer/astronomer/pull/2301

our original intention was to mix it up with global.rbacEnabled so that we will be removing the serviceAccount section from all the templates, with the redefined approach we configured our helper templates to use default service account when serviceAccount create is set to false and no name is defined it will fallback the serviceAccountName to default 

## Related Issues

https://github.com/astronomer/issues/issues/6537
https://github.com/astronomer/issues/issues/6583

## Testing

refer notion doc

## Merging

cherry-pick to release-0.36

### CODE REVIEW

**Comment by danielhoherd** [comment]
@pgvishnuram what is the context here? why is this change needed?

**Review by rishkarajgi — CHANGES_REQUESTED** [review]
Update PR description on what is the issue you are addressing, why these changes are needed and if any breaking changes. Add link to Notion doc

**Comment by pgvishnuram** [comment]
This is an update from previous PR where we missed to remove the rbac conditions

**Review by rishkarajgi — CHANGES_REQUESTED** [review]
please update the PR description. Add details on why are doing this change and what is the problem we are trying to solve

**Comment by pgvishnuram** [comment]
@rishkarajgi this is a missed commit from the list of changes we introduced in PR https://github.com/astronomer/astronomer/pull/2301

**Review by rishkarajgi — APPROVED** [review]

**Review by rishkarajgi — CHANGES_REQUESTED** [review]
Still don't understand the context, what is the need to remove `if .Values.global.rbacEnabled` wrt BYO service accounts?

**Review by rishkarajgi — APPROVED** [review]

**Pull request merged**
