### PR TITLE
bump houston-api and astro-ui to 0.22

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## 🎟 Issue(s)

based on https://app.circleci.com/pipelines/github/astronomer/houston-api/2565/workflows/7c8e8ba0-fb93-4a05-8736-932be4f90a72/jobs/8806

## 📋 Checklist

- [ ] The PR title is informative to the user experience

### CODE REVIEW

**Comment by adam2k** [comment]
Can we include Astro UI here too and then we can update the title of the PR?

**Review by adam2k — APPROVED** [review]
I don't know if you wanted to add Astro UI to this or do it in another PR.  I think either is OK.

**Comment by andriisoldatenko** [comment]
@adam2k done.

**Review by tommyk — APPROVED** [review]
looks good to me, but i am just following along to try and understand the steps for deployments.

**Review by jpweber — APPROVED** [review]

**Pull request merged**
