### PR TITLE
bump images

### PR DESCRIPTION
**Pull request by andriisoldatenko**
Marge after related PRs will be merged
- [x] https://github.com/astronomer/install.astronomer.io/pull/3
- [x] https://github.com/astronomer/db-bootstrapper/pull/11
- [x] https://github.com/astronomer/airflow-chart/pull/70
- [x] https://github.com/astronomer/houston-api/pull/258

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
`docker pull astronomerinc/ap-cli-install:0.13.0` done

**Comment by sjmiller609** [comment]
waiting for CI to pass.

**Comment by andriisoldatenko** [comment]
related PR https://github.com/astronomer/ap-vendor/pull/18/files

**Comment by andriisoldatenko** [comment]
**pls don't merge**
@dimberman found bug, i can reproduce it with airflow-chart 0.13.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF session token is missing.</p>
```

**Comment by sjmiller609** [comment]
I'm going to merge just for the sake of getting it all together on dev cloud, we can releases another patch version for an image if needs one

**Pull request merged**
