### PR TITLE
support global.kubedEnabled in houston

### PR DESCRIPTION
**Pull request by andriisoldatenko**
resolves https://github.com/astronomer/issues/issues/3900

### CODE REVIEW

**Comment by danielhoherd** [comment]
@andriisoldatenko we should discuss the rollout of this change in standup.

**Comment by andriisoldatenko** [comment]
@danielhoherd yes sure, i've created document https://www.notion.so/astronomerio/Remove-KubeD-76a8ee8f49e54f02a4e489079aa7193d

**Review by danielhoherd — CHANGES_REQUESTED** [review]
@andriisoldatenko needs tests.

**Comment by andriisoldatenko** [comment]
@danielhoherd yep working on it right now!

**Comment by andriisoldatenko** [comment]
@danielhoherd i've added tests.

**Comment by danielhoherd** [comment]
It's interesting that [we already had support for `global.kubedEnabled` in the chart](https://github.com/astronomer/astronomer/blob/d4088bfba9/Chart.yaml#L61-L65), but the default wasn't set in values.yaml.

**Review by danielhoherd — APPROVED** [review]
LGTM. We'll have to add more kubed tests in another PR. [I'm already working on extending our test coverage in another branch](https://github.com/astronomer/issues/issues/3870) and have [added some simple tests to cover enabled and disabled kubed there](https://github.com/astronomer/astronomer/commit/24b143e2acffd00cfad8f2c6c45639e4b7264c96).

**Pull request merged**
