### PR TITLE
update Astro CLI version to latest verison

### PR DESCRIPTION
**Pull request by fritz-astronomer**
this should probably be updated via CICD somehow?

## 🎟 Issue(s)
Fixes  https://github.com/astronomer/issues/issues/2802

### CODE REVIEW

**Review by andriisoldatenko — APPROVED** [review]

**Review by bote795 — APPROVED** [review]

**Comment by vishwas-astro** [comment]
Should we also fix the release-0.23 branch to point to the right CLI version?

@bote795 could you also spend a little bit of time thinking about where in our CI we could automate this?

**Comment by bote795** [comment]
> Should we also fix the release-0.23 branch to point to the right CLI version?
> 
> @bote795 could you also spend a little bit of time thinking about where in our CI we could automate this?
I think we can, for future installs, I know for issue they found a workaround. 
created the following issue to help with CI release for astro-cli, https://github.com/astronomer/issues/issues/3480

**Comment by vishwas-astro** [comment]
@bote795 Are you saying because the workaround exists, we don't need to fix the release-0.23 branch and release-0.25 branches?

@fritz-astronomer @fhoda are you two cool with that? This will be fixed in 0.26.0 and later platform versions?

**Comment by bote795** [comment]
can we merge this? @fritz-astronomer

**Comment by fritz-astronomer** [comment]
I am not able to - but anyone is welcome to

**Review by danielhoherd — APPROVED** [review]

**Pull request merged**
