### PR TITLE
Merge master into release-0.23

### PR DESCRIPTION
**Pull request by danielhoherd**
Rather than cherry-picking changes that have been merged to master, let's merge the whole branch so that it stays in sync.

### CODE REVIEW

**Review by sjmiller609 — APPROVED** [review]
Looks good, but I would like my LTS upgrader thing in here also

**Comment by danielhoherd** [comment]
> Looks good, but I would like my LTS upgrader thing in here also

I think anything that gets merged into master will be included. That is the normal behavior of PRs from feature->master, so I would expect it to work the same from master->feature

**Comment by danielhoherd** [comment]
Oh, interesting... we can't not squash-and-merge here, because it's not enabled for the repo.

**Comment by danielhoherd** [comment]
I manually merged these changes and pushed them, in order to avoid having to squash and merge.

**Review by ianstanton — APPROVED** [review]

**Pull request merged**
