### PR TITLE
5137 fix schema validation

### PR DESCRIPTION
**Pull request by danielhoherd**
## Description

Fix schema validation by using strict schema. We ran into some networkPolicy errors that should have been caught by schema validation. Using strict caught them, and another error that existed in our chart.

While debugging the schema validation problem I also added a previously impossible test by adding headers to some templates. And while adding those headers, I lined up some header contents on some other files.

## Related Issues

https://github.com/astronomer/issues/issues/5137

## Testing

These are tests. I don't think any further testing needs to be done.

## Merging

AFAIK these changes should be merged into all supported branches.

### CODE REVIEW

**Review by pgvishnuram — APPROVED** [review]
externalIPs - we have not noticed the typo error

**Comment by danielhoherd** [comment]
Merged and cherry-picked the relevant schema validation and externalIPs changes to all supported branches. The header changes and np_disabled stuff didn't apply to all branches so that was left out if it wasn't relevant.

**Comment by vishwas-astro** [comment]
@danielhoherd Will require a 0.30.3-rc3 if we want this included in 0.30.3.

**Comment by danielhoherd** [comment]
@vishwas-astro this is not an urgent change. There was a bug fix, but no customers had complained about it, so it's very likely going to be a no-op for everybody. The real meat of this change is we are getting better k8s schema validation, which would have caught a bug during dev iterations on a recent feature addition.

**Pull request merged**
