### PR TITLE
bump es and kibana to 7.7.1

### PR DESCRIPTION
**Pull request by andriisoldatenko**
to follow up https://github.com/astronomer/ap-vendor/pull/28

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@vishwas-astro i would like to have it also in 0.16.x

**Comment by vishwas-astro** [comment]
@andriisoldatenko i am cool with that, as long as we test the corresponding product features that are affected thoroughly in KinD/dev/stage etc.

**Comment by andriisoldatenko** [comment]
yep i tested it in kind.

**Comment by andriisoldatenko** [comment]
@schnie please merge 
practically LGTM tested in dev cluster.

**Pull request merged**
