### PR TITLE
add ablity to use option when random data

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by vishwas-astro** [comment]
This PR looks like a no-op to me.

**Comment by vishwas-astro** [comment]
What about other changes from this PR: https://github.com/astronomer/astronomer/pull/1115/files?

**Comment by andriisoldatenko** [comment]
@vishwas-astro because i'm still working on it.

**Comment by andriisoldatenko** [comment]
> What about other changes from this PR: https://github.com/astronomer/astronomer/pull/1115/files?

other changes already in master
```
https://github.com/astronomer/astronomer/blob/master/charts/astronomer/templates/registry/registry-statefulset.yaml#L58-L63
```

**Comment by andriisoldatenko** [comment]
closing since all commits already in master:

https://github.com/astronomer/astronomer/blob/master/charts/astronomer/templates/_helpers.yaml#L64-L72
https://github.com/astronomer/astronomer/blob/master/charts/astronomer/templates/registry/registry-statefulset.yaml#L58-L63

**Pull request closed without merging**
