### PR TITLE
Fix for DB migration of Airflow version 1.10.6

### PR DESCRIPTION
**Pull request by ashb**
I went to check my hot fix for Houston had made it to master (it hadn't) and noticed this commit needed doing to.

(cherry picked from commit e1750670bdbb618f16c43507ce290da847f6243a)

### CODE REVIEW

**Comment by schnie** [comment]
These make me worried. Is there a reason we can't merge things to master first as a practice?

**Comment by sjmiller609** [comment]
it's a dupe of https://github.com/astronomer/astronomer/pull/711/files

**Comment by sjmiller609** [comment]
@schnie the reason is because I can push to release branches but not master. in a hotfix scenario where I need to release immediately, I push directly to release branch then ship to cloud.

**Comment by ashb** [comment]
@sjmiller609 Not entirely -- on master the version in the charts is still wrong.

**Comment by sjmiller609** [comment]
deprecated - we have a different version of houston up

**Pull request closed without merging**
