### PR TITLE
rework serviceAccountName with standard naming conventions

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

rework serviceAccountName with standard naming conventions

## Related Issues

- https://github.com/astronomer/issues/issues/6747

## Testing

NA

## Merging

NA

### CODE REVIEW

**Review by rishkarajgi — COMMENTED** [review]
please update/add necessary tests

**Comment by pgvishnuram** [comment]
@rishkarajgi we already have covered tests wrt to service account this is a templating naming change to have same naming across all service account templates

**Review by Shubham-astro — APPROVED** [review]
Looks good...

**Comment by Shubham-astro** [comment]
@pgvishnuram, I think the values.yaml file also need to be changed to use serviceAccountName, I see most of the values file are currently using serviceAccount. 
For example:
https://github.com/astronomer/astronomer/blob/master/charts/stan/values.yaml#L35

**Review by danielhoherd — CHANGES_REQUESTED** [review]
These still need to be updated:
- https://github.com/astronomer/astronomer/blob/08d8264235/charts/astronomer/templates/registry/registry-scc.yaml#L11
- https://github.com/astronomer/astronomer/blob/08d8264235/charts/astronomer/templates/registry/registry-scc.yaml#L23

**Review by rishkarajgi — APPROVED** [review]

**Pull request merged**
