### PR TITLE
fix network communication issue  if calico/network plugins are enabled

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

Once sidecar logging enabled and calico is installed , it will cause network issue due to the restriction in connecting elasticsearch client. Initially only webserver was allowed to connect es client.

Why this issue is not observer earlier ?

All the log related stuffs are taken care by fluentd. 

## Related Issues

https://github.com/astronomer/issues/issues/4612

## Testing
while setting up aws users qa team should additionally install calico to test this behavior

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@danielhoherd and @vishwas-astro 

Im unable to restrict this if for only logging sidecar is enabled due to the values are from platfrom subchart

**Comment by pgvishnuram** [comment]
@danielhoherd - can you merge this

**Comment by santoshr1016** [comment]
@danielhoherd @pgvishnuram Just my thoughts on testing.. Ideally the unit test cases should catch the communication paths. 
The network policies should be tested using the real test pods from the different namespaces, there should be positive test cases and negative test cases.
test-fail-from-nginx-wrong-namespace
test-success-from-nginx-namespace
test-service-from-elastic
test-from-anywhere
and I think its the integration tests too...
The present unit test is checking the netpol syntax, which is okay.

Also nit @pgvishnuram  
It would be great if the network policie yaml, nginx-es-networkpolicy.yaml is renamed to 
es-ingress-networkpolicy.yaml (idea is tell what is policy doing)

**Comment by pgvishnuram** [comment]
nginx-es is the component name, if it's replaced nginx-es-ingress-networkpolicy.yaml  it should be okay

**Review by santoshr1016 — APPROVED** [review]
LGTM, will iterate in coming sprints

**Pull request merged**
