### PR TITLE
Add missing commits from 0 13

### PR DESCRIPTION
**Pull request by andriisoldatenko**
git cherry -v release-0.13 | grep +
+ e9b3271b040e816ef1366341ee9cda6cd2c4df70 Add configuration to re-generate CA on each upgrade (#627)
+ f890251efd8de84e2e9f3e863393e7f90636ce66 Add upgrade script (#630)
+ 863f1c2da29f3fed839b3d2d0a3a903c2a7de211 Add example IKS fluentd config (#632)
+ 6cbd67854c176c80d550565135bd9ac4c90e5b65 Make the probes more configurable (#636)
+ dc5cef1f3fd6a1475b8c0a1899aa2d30f03047fc Made scrape intervals less frequent (#628)
+ 2c3aafd94a5e9dd7cedff70771fc8b13844ff507 Add namespace var to upgrade_version_in_astro_db (#637)
+ 81fe3031d6c1cecb0a0ff444de93fd6cd630b1a0 Add list of other supported images (#640)
+ 2423fe547e01ec1827a1f168d1e30cf3fa5a42a3 Houston 0.13.3 and reconfigure resources on blackbox exporter (#646)
+ 7b4dd139998d7d4e96bc2c281b7aa71b4190e016 Add secret block back into Houston environment (#644)
+ a7ebb2773141945feaec9fc85a9d20e8930789f0 Add secret block back into Houston environment (#644)
+ 8de66e3bc88a73ef45b3bc2af0ec6563279ec134 Houston 0.13.4
+ 1eca1f0e06976821c91d026ee9b607070c82ccf7 Astro UI 0.13.1
+ 7be22490f6dcf47ec8a61232333d7b70bf1e68c6 Specify new name for signing cert in upgrade script (#645)
+ 3f38773a5baf6666d9db8be30d20ec30f2925cf6 Astro UI 0.13.2
+ f94bbba807f87c9c1c94c86d16a4ea973a18a8c8 Raised the default cpu limit of blackbox exporter (#651)
+ 2228fd7d01c3bc5378381d986308d44fd57dfd09 Added scrape job for kube-apiservers. (#653)
+ 9ffcb4c4f214b324d900ef018e7ad03065f93cc3 Add SECURITY.md for security notes
+ 5550941cf638d3582922438351f8f4d88b12aa0b Revise note
+ 2ea21c2ed605d892f8c47254cb3ac19a835cb715 Update README.md
+ 8bed4a7c887470d4681656844f535f1441bee85f Add ap-airflow 1.10.10 Images to Supported list (#655)
+ 96032eed839a962d9461d795058cf10c055ac5d1 Updates to CPUThrottlingHigh and Nginx 5xx and 4xx alerts (#652)
+ 66c63c55d85d3d426549fba5ccadb19e3faed652 Reformat so item can be linked
+ 6c977a3abe15945022fb7f1d6a6b272b7cf1ccad Changed $labels.release to $labels.deployment (#658)
+ 722f7f547f7ceba570da6e2cb8361faad17281d3 add tolerations to KEDA helm chart (#660)
+ a8ea42682b93fc6cf61522decd62f98830fce514 sadly appears you can't template a values.yaml (#662)
+ a3c5482a74098ca4a299dbd537ad06145baf8976 Helm 3
+ d7610a5d018a82e7943900b4c80c3914391f03ee Updated fluentd to use image with bugfux (#663)

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@schnie @sjmiller609 PTAL

**Comment by schnie** [comment]
Looks like we have some conflicts. Maybe since I merged @jpweber's earlier commit to backport some things?

**Comment by jpweber** [comment]
I can work through these conflicts because I'm pretty sure its exactly what greg said and I know where they are.

**Comment by jpweber** [comment]
Merge conflicts resolved.

**Comment by ashb** [comment]
Is it worth (manually, via CLI) merging this one rather than squash to preserve the individual commits?

**Comment by andriisoldatenko** [comment]
@ashb please explain yourself?

**Comment by ashb** [comment]
Merge commit:

image

Squash commit (which is all we allow via the Github UI:)

image

**Comment by schnie** [comment]
Merged preserving original commits.

**Pull request merged**
