### PR TITLE
Refactored using mkcert

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@sjmiller609 pls point me where to add new tool: `https://github.com/FiloSottile/mkcert`
@schnie confirmed this approach works well.

**Comment by andriisoldatenko** [comment]
image

**Comment by schnie** [comment]
This is failing to fully install for me. Stops after tiller and doesn't install the platform :thinking: 

```
mkcert is in PATH
kind is in PATH
helm is in PATH
kubectl is in PATH
docker is in PATH
Generating SSL keys...
Using the local CA at "/home/schnie/.local/share/mkcert" ✨
The local CA is already installed in the system trust store! 👍
The local CA is already installed in the Firefox and/or Chrome/Chromium trust store! 👍

Using the local CA at "/home/schnie/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "app.local.astronomer-development.com"
 - "*.local.astronomer-development.com"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.local.astronomer-development.com ℹ️

The certificate is at "./app.local.astronomer-development.com+1.pem" and the key at "./app.local.astronomer-development.com+1-key.pem" ✅

Installed TLS secrets to /tmp/fullchain.pem and /tmp/privkey.pem
++ kind delete cluster
Deleting cluster "kind" ...
++ kind create cluster --image kindest/node:v1.15.6
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.6) 🖼
 ✓ Preparing nodes 📦 
 ✓ Creating kubeadm config 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl cluster-info
++ set +x
NAME                 STATUS     ROLES    AGE   VERSION
kind-control-plane   NotReady   master   4s    v1.15.6
Creating Tiller service account...
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
Installing tiller in the KinD cluster...
```

**Comment by sjmiller609** [comment]
@andriisoldatenko awesome!! thank you for this. I'm currently working to add CI into this repo and the airflow repo.

**Comment by andriisoldatenko** [comment]
@schnie works for me:
```
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
++ set +x
`kind get kubeconfig-path` is deprecated!

KIND will export and merge kubeconfig like kops, minikube, etc.
This command is now unnecessary and will be removed in a future release.

For more info see: https://github.com/kubernetes-sigs/kind/issues/1060
See also the output of `kind create cluster`

NAME                 STATUS     ROLES    AGE   VERSION
kind-control-plane   NotReady   master   6s    v1.15.6
Creating Tiller service account...
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
Installing tiller in the KinD cluster...
Tiller installed.
Creating namespace 'astronomer'
namespace/astronomer created
Installing TLS cert and private key
secret/astronomer-tls created
```

**Comment by andriisoldatenko** [comment]
```
(base) ➜  astronomer git:(add-mkcert-to-kind) ✗ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
astronomer      1               Sat Jan 25 00:01:41 2020        DEPLOYED        astronomer-platform-0.11.0      0.11.0          astronomer
postgresql      1               Sat Jan 25 00:00:56 2020        DEPLOYED        postgresql-8.1.4                11.6.0          astronomer
```

**Comment by sjmiller609** [comment]
@schnie perhaps you are discovering a race condition in the script between the kind script returning and the kube api being ready, or maybe you are not waiting long enough ...? I do not see an error, does it just hang?

**Comment by schnie** [comment]
Looks like `tiller` was hanging in `Pending` state because it couldn't find a node. For some reason the cni plugin was failing on the node. Rebooted my laptop and it worked :tada:

**Pull request merged**
