### PR TITLE
blackbox exported disabled by default

### PR DESCRIPTION
**Pull request by jpweber**
## Description

Changes the default value from `enabled` to `disabled` for the blackbox exporter component of the astronomer chart. 

## 🎟 Issue(s)

Resolves https://github.com/astronomer/issues/issues/2248

### CODE REVIEW

**Comment by sjmiller609** [comment]
I think the unit tests need adjustment

**Comment by jpweber** [comment]
@sjmiller609 Pushed update here with out the tests that can't pass now. Have another look.

**Review by sjmiller609 — APPROVED** [review]

**Comment by vishwas-astro** [comment]
@jpweber while you are at it, can you cherry pick to 0.23 branch please?

**Comment by jpweber** [comment]
@vishwas-astro cherry picked.

**Pull request merged**
