### PR TITLE
Integrate Prisma Cloud Docker Image Scans

### PR DESCRIPTION
**Pull request by mishah334**
## Description

Adding integration of Prisma Cloud Docker Image Scans using `twistcli`.

## Related Issues

N/A

## Testing

This change was tested directly by calling the Circleci job. 

Example: https://app.circleci.com/pipelines/github/astronomer/astronomer/9133/workflows/91275c9f-c0c4-4ebb-8b34-6ddb354196b3

## Merging

All active releases.

### CODE REVIEW

**Comment by vishwas-astro** [comment]
Mishal, isn't twistcli from Prisma and not Prima?

Also, was this change initiated by Zac and his security team (Ryan restivo and Victor Lucas)?

**Review by rishkarajgi — APPROVED** [review]

**Comment by rishkarajgi** [comment]
pre-commit and tests failing

**Review by rishkarajgi — CHANGES_REQUESTED** [review]
pre-commit and tests failing

**Comment by mishah334** [comment]
> Prisma

Yes, it is Prisma, Sorry for the typo. Victor Lucas suggested this practice. We connected last week to discuss the Prisma Cloud.

**Comment by mishah334** [comment]
> pre-commit and tests failing

Merging`master` branch made it fail because of the updated image. Added a fix.

**Review by rishkarajgi — APPROVED** [review]

**Pull request merged**
