### PR TITLE
Allow for configurable SSL mode

### PR DESCRIPTION
**Pull request by ianstanton**
## Description
- Allow for configurable SSL mode through `.Values.global.ssl.mode`
- Default to `prefer`
- Grafana env var `GF_DATABASE_SSL_MODE` is still hardcoded with `require`. `prefer` is not an acceptable mode for this.
- This mode will be passed to:
  - `bootstrapper` container in grafana deployment
  - `houston-bootstrapper` container in houston-worker-deployment
  - `houston-bootstrapper` container in houston-db-migration-job
  - `houston-bootstrapper` container in houston-deployment
  - Each Airflow at `.Values.data.resultBackendConnection.sslmode`

## 🎟 Issue(s)
- Resolves astronomer/issues#2423

## 📋 Checklist

- [x] The PR title is informative to the user experience

### CODE REVIEW

**Comment by ianstanton** [comment]
I'm not sure if this should be merged into `master` or `release-0.23` branch.

**Comment by danielhoherd** [comment]
I like the new structure better than the old one. IMHO this would be great to merge before we release 0.23 publicly because it would be great to get it in sooner than later. Adding this will require docs changes and customer communications, would require upgrade script modification, and would likely be a source of customer issues, so we'll want to rope in folks related to those areas. @paolaperaza @krisdock @sjmiller609

**Comment by paolaperaza** [comment]
@danielhoherd Thanks for the tag here - hadn't been keeping track of this. I presume merging this PR will affect the work @jwitz is doing with @sjmiller609 on SSL related documentation, but only for 0.23+?

@jwitz I'll have you keep tabs on this as needed - follow along if the convo continues here and just double check before we merge the docs PR (#983) that changes here are reflected in the `/next/` version of the file, or wherever is applicable. Thank you!

**Review by schnie — APPROVED** [review]

**Review by jpweber — APPROVED** [review]

**Comment by vishwas-astro** [comment]
@ianstanton I think this should be merged to master branch and then cherry picked into 0.23 branch.

**Comment by vishwas-astro** [comment]
@jpweber OR @schnie can one of you merge this as @ianstanton does not have merge rights?

**Comment by vishwas-astro** [comment]
@ianstanton can you please cherry pick this into 0.23 release branch?

**Comment by ianstanton** [comment]
@vishwas-astro  i spoke with @danielhoherd and he is going to open a PR to merge `master` into `release-0.23`

**Pull request merged**
