### PR TITLE
update to postgresql image 14.4.0-debian-11-r4

### PR DESCRIPTION
**Pull request by santoshr1016**
## Description
Update the postgressql image to 4.4.0-debian-11-r4 to address few vulnerabilities, But there are still few which have been added to the trivy ignore for which the upstream fix is not yet available.
The change addressess [issue](https://github.com/astronomer/issues/issues/4658)

## Related Issues

NA

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

### CODE REVIEW

**Review by andriisoldatenko — APPROVED** [review]

**Comment by vishwas-astro** [comment]
@pgvishnuram - can you merge this and build the ap-postgresql image please?

**Comment by pgvishnuram** [comment]
Okay sure

**Comment by danielhoherd** [comment]
During standup today we agreed to not merge this until astronomer/astronomer version 0.30.0 in order to avoid breaking environments where folks are running the existing postgres version. We want to make this big version jump not in a patch release.

**Review by danielhoherd — CHANGES_REQUESTED** [review]
PR description needs to be completed.

**Pull request closed without merging**
