### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by ashb** [comment]
What's the interaction between this and ap-vendor. Why do we need too update version in two places

**Comment by andriisoldatenko** [comment]
@sjmiller609 wdyt?

**Comment by schnie** [comment]
ap-vendor is what pushes the new 0.30.0 tag of the image. This is what pulls that tag into the default deployment. We've talked about automating this PR though, just haven't gotten to that part of the pipelines yet.

**Comment by schnie** [comment]
I think this PR should also have gone to master and cherry-picked to the release branch, but we can cherry-pick this one to master once we merge it.

**Pull request merged**
