### PR TITLE
add scc privileges for openshift external logging service

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

This PR allows external es proxy service to run in openshift with custon userid as a non root process

## PR Title

add scc privileges for openshift external logging service

## 🎟 Issue(s)

https://github.com/astronomer/issues/issues/3259

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@danielhoherd

**Review by danielhoherd — CHANGES_REQUESTED** [review]
Looks fine, but needs tests.

**Review by danielhoherd — APPROVED** [review]
Looks good. We don't have an openshift schema validator test setup right now but here is an issue to track that for future use https://github.com/astronomer/issues/issues/3909

**Comment by danielhoherd** [comment]
@pgvishnuram is this good to merge? I just noticed I approved it over a month ago but never merged it.

**Review by danielhoherd — APPROVED** [review]

**Comment by pgvishnuram** [comment]
lets merge this

**Pull request merged**
