### PR TITLE
Correct externalTrafficPolicy behavior. Add tests.

### PR DESCRIPTION
**Pull request by danielhoherd**
https://github.com/astronomer/astronomer/issues/1035 Pointed out that we are explicitly setting what is already the default behavior of nginx, and while doing so we are doing the opposite of what the configured behavior should be. This change set corrects the behavior and adds unittests for that aspect of the chart.

### CODE REVIEW

**Review by tommyk — APPROVED** [review]
might want to make sure this gets documented as i feel like its a breaking change you are making, right? 

(even though you are fixing a bug, it feels like the behavior will be the opposite as before?)

**Comment by danielhoherd** [comment]
@jwitz @paolaperaza @krisdock what do you all think about this change?

**Comment by danielhoherd** [comment]
Next up we should migrate the helm-unittest in this branch to be a pytest test. That way we can be more confident in this change.

**Comment by danielhoherd** [comment]
If we are going to move forward with this the tests need to be rewritten in pytest.

**Comment by pgvishnuram** [comment]
we can remove the helm test file for this change

**Comment by danielhoherd** [comment]
@pgvishnuram I deleted the helm-unittest test. Do you think this is ready to merge? My worry is still that we are changing behavior on existing installations.

**Comment by andriisoldatenko** [comment]
LGTM

**Review by andriisoldatenko — APPROVED** [review]

**Pull request merged**
