### PR TITLE
update platform images

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

 * bump ap-houston-api 0.31.13 -> 0.31.14
* bump ap-astro-ui 0.31.9 -> 0.31.10
 * bump ap-db-bootstrapper  0.26.14 -> 0.31.0

## Related Issues

https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.31.2

## Testing

No special testing is needed. Normal test cycle will suffice.

## Merging
0.31.2

### CODE REVIEW

**Comment by pgvishnuram** [comment]
pytests are failing checking this issue

**Comment by pgvishnuram** [comment]
@danielhoherd - we are adding ALLOW_CONFIG_MUTATIONS env vars to houston common vars - do you see any issues

**Comment by pgvishnuram** [comment]
@danielhoherd @rishkarajgi added test case to validate ALLOW_CONFIG_MUTATIONS

**Comment by danielhoherd** [comment]
@pgvishnuram AFAIK ALLOW_CONFIG_MUTATIONS is a dev feature and should not be present here. Maybe @bote795 would have more info?

**Comment by bote795** [comment]
> ALLOW_CONFIG_MUTATIONS

sorry i have no context on this

**Comment by rishkarajgi** [comment]
> @pgvishnuram AFAIK ALLOW_CONFIG_MUTATIONS is a dev feature and should not be present here. Maybe @bote795 would have more info?

This env variable is an addition as a requirement for the new node-config npm package to operate

**Comment by danielhoherd** [comment]
`ALLOW_CONFIG_MUTATIONS` should live in the Dockerfile of the component, not the kubernetes environment, *especially* if it's required for houston to operate.

**Review by rishkarajgi — APPROVED** [review]

**Comment by pgvishnuram** [comment]
@danielhoherd moved the env vars to houston dockerfile - removed all the changes made in astronomer chart

**Review by danielhoherd — APPROVED** [review]
```
 _      _____ _______ __  __
| |    / ____|__   __|  \/  |
| |   | |  __   | |  | \  / |
| |   | | |_ |  | |  | |\/| |
| |___| |__| |  | |  | |  | |
|______\_____|  |_|  |_|  |_|
```

**Review by danielhoherd — CHANGES_REQUESTED** [review]
PR description needs to be completed.

**Pull request merged**
