### PR TITLE
prepare release 0.23.4

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## 📋 Checklist

- [ ] The PR title is informative to the user experience

### CODE REVIEW

**Comment by vishwas-astro** [comment]
I guess you could just update the astronomer image version also to 0.23.4 in this same PR

**Comment by andriisoldatenko** [comment]
> I guess you could just update the astronomer image version also to 0.23.4 in this same PR

@vishwas-astro  do you mean astronomer chart version?

**Comment by vishwas-astro** [comment]
> > I guess you could just update the astronomer image version also to 0.23.4 in this same PR
> 
> @vishwas-astro do you mean astronomer chart version?

Yes!

**Comment by vishwas-astro** [comment]
@andriisoldatenko you could include airflow-chart-0.18.6 in this PR

**Review by kushalmalani — APPROVED** [review]

**Pull request merged**
