### PR TITLE
Bump astro-ui 0.34.2 houston-api 0.34.4

### PR DESCRIPTION
**Pull request by rishkarajgi**
## Description

Bump astro-ui 0.34.2 houston-api 0.34.4

## Related Issues

Do not merge this PR until this text is replaced with links to related issues.

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

release-0.34

### CODE REVIEW

**Comment by pgvishnuram** [comment]
No files ??

**Comment by pgvishnuram** [comment]
it should go to master first

**Comment by rishkarajgi** [comment]
> it should go to master first

Master is not in sync

**Comment by pgvishnuram** [comment]
supersed by PR https://github.com/astronomer/astronomer/pull/2120

**Pull request closed without merging**
