### PR TITLE
Turn on NATs integration and add RBAC for environment variables

### PR DESCRIPTION
**Pull request by kushalmalani**
astronomerinc/ap-houston-api:0.19.0

Features added:
> b07a349 Adjust defaultExtraAu validation (#420)
> 2506cb9 Replacing mapCustomEnvironmentVariables with secretName (#415)
> 3f49554 fix: upgrade openid-client from 3.15.8 to 3.15.9 (#421)
> afc16f8 Wait for NATS Host and Port (#423)
> f51e48f Fix flakey test (#359)
> e66c4a3 Implement NATS Update Deployments (#412)
> bcfe6ad Enable Delete and Create Deployment Workers (#417)
> eaca3d4 fix: package.json & yarn.lock to reduce vulnerabilities (#419)
> 10c0d98 Update code coverage minimum (#418)
> 24213c3 add nats cluster to docker-compose-nats-cluster.yml (#386)
> 1c6e40d Create wrapper for publisher error handling (#411)
> 79bfbd2 fix: upgrade multiple dependencies with Snyk (#409)
> 21d8ea0 Update workers codeowners (#410)
> 8c81f2f Add baseline editorconfig file (#408)
> 58948cb PR template tweaks proposal (#407)
> e210096 fix: upgrade email-templates from 7.0.5 to 7.1.0 (#402)
> 9809ffa Remove old folder location (#406)
> 258f15c Add first draft of PR template (#405)
> e0902d3 Catch publish errors when connection is severed (#403)
> d3af2c2 Fix: Prevent duplicate service account (#404)
> 6ff92c2 Add fine-grained role permissions for deployment variables (#390)

### CODE REVIEW

**Comment by sjmiller609** [comment]
Can you please change the PR title to reflect the user experience? For example explaining what features are in this compared to previous versions

**Comment by kushalmalani** [comment]
> Can you please change the PR title to reflect the user experience? For example explaining what features are in this compared to previous versions

I added them to the description. Too many changes to go into the title block

**Comment by andriisoldatenko** [comment]
why do we need this PR?

**Comment by andriisoldatenko** [comment]
> agreed with @sjmiller609 please simplify description.

@kushalmalani wdyt?

"Add NATS deployment, optimizing secret mangement, adding fine-grained role permissions for deployment variables "

**Comment by sjmiller609** [comment]
Also, this change is introducing something that causes airflow deploys to not work, check out the CI output

**Comment by sjmiller609** [comment]
```
astronomer-planetoidal-precession-2433   planetoidal-precession-2433-worker-64d97c8c48-xtzct        0/1     CreateContainerConfigError   0          10m
```

**Comment by andriisoldatenko** [comment]
> ```
> astronomer-planetoidal-precession-2433   planetoidal-precession-2433-worker-64d97c8c48-xtzct        0/1     CreateContainerConfigError   0          10m
> ```

may be related to https://github.com/astronomer/airflow-chart/pull/113 ?

**Pull request merged**
