### PR TITLE
Refactor and improve local test code. Trim some cruft.

### PR DESCRIPTION
**Pull request by danielhoherd**
## Description

This change set improves the local dev experience by making the `bin/run-ci` code path workstation safe, improving the Makefile by adding new targets and help text, and by removing broken and dangerous targets.

## 🎟 Issue(s)

Resolves astronomer/issues#1738

## 🧪  Testing

Risks in this change are mostly around breaking workflows that may have relied on pre-rework behavior that has been syntactically fixed, but might cause functional breakage. (EG: whitespace splitting).

Given that these changes are related to test running, there's little risk that the chart itself will experience problems. All changes are related to dev and CI workflows.

One big goal here was to make the whole `bin/run-ci` flow not interfere with the developer system at all. It is possible I missed something, and if so we should fix it either before merging this or when it is found.

## Highlights of what changed
- Removed some old make targets that incorrectly modified a bunch of versions, and allowed pushing these incorrect versions to prod.
- Added `make help` text. `help` is now the default target.
```
$ make help
build                Build the helm chart for distribution
clean                Clean all artifacts
help                 Print Makefile help
lint-astro           Lint the Astronomer helm chart
lint-charts          Lint all Helm charts
lint-clean           Delete lint artifacts
lint-prom            Lint the prometheus helm charts
lint                 Run all lint steps
local-test           Run a local chart test in kind
test                 Run unittests and local kind tests
unittest-charts      Run helm unittests on all charts
venv                 Create the necessary python venv
```
- Simplified and cleaned up several scripts.
- Renamed some variables to be more descriptive.

### CODE REVIEW

**Comment by sjmiller609** [comment]
@danielhoherd hey sorry it took me so long to review this PR. Can you please handle merge conflicts, I'll take another look and get this in.

**Comment by sjmiller609** [comment]
thank you

**Comment by jpweber** [comment]
This has collected more merge conflicts. Can we these sorted out and get this merged before it stays open for too much longer and picks up more conflicts.

**Comment by danielhoherd** [comment]
I've converted this to a draft because it's not working yet, and honestly it's not all that important. It was a bit of a rabbit hole.

**Comment by danielhoherd** [comment]
Closing stale PR.

**Pull request closed without merging**
