### PR TITLE
Cherrypick "k8s 1.22, 1.23 support (#1401)" into release-0.28

### PR DESCRIPTION
**Pull request by pgagnon**
## Description

Backport "k8s 1.22, 1.23 support (#1401)" to the 0.28 release series.

0.28 is currently our latest stable release and K8s 1.22 support is required on AKS to use agents with containerd 1.5, which is required in order to support private CAs.

## Related Issues

#1401 , astronomer/issues#3889 , astronomer/issues#4363

## Testing

WIP

## Merging

release/0.28

### CODE REVIEW

**Comment by danielhoherd** [comment]
CC @cmarteepants

**Comment by pgvishnuram** [comment]
please halt this merge until we get input from @cmarteepants

**Comment by pgvishnuram** [comment]
we need to release new airflow chart as well if 1.22 support is backported to 0.28

**Comment by danielhoherd** [comment]
@pgvishnuram we're still not proceeding with this until @cmarteepants gives the go-ahead. i have a feeling we will not do this.

**Comment by cmarteepants** [comment]
circumstances changed - we're fine to backport support. thanks for following up

**Comment by danielhoherd** [comment]
OK, with that in mind, we will need to figure out the airflow-chart needs for the 0.28 support of k8s >= 1.22

**Comment by danielhoherd** [comment]
I chatted with @pgvishnuram yesterday and he said he's picking up the rest of the work that needs to be done to close out this issue.

**Comment by pgvishnuram** [comment]
testing all the related changes

**Comment by pgvishnuram** [comment]
we can merge this change

**Pull request merged**
